import { Language } from "../types";

export const translations = {
  en: {
    appTitle: "🚀 Yancy’s Mathetris",
    config: {
      maxNumber: "Max Number in Question",
      maxAnswer: "Max Answer Value",
      steps: "Calculation Steps",
      position: "Question Position",
      posRight: "Right (a + b = ?)",
      posLeft: "Left (? + b = c)",
      posMixed: "Mixed",
      speed: "Target Time (Speed)",
      secPerProb: "seconds / problem",
      totalQ: "Total Questions",
      randomDiff: "Difficulty Randomization",
      randomDiffDesc: "Mix easier types",
      instantFeedback: "Instant Feedback",
      instantFeedbackDesc: "Show errors immediately",
      startBtn: "Start Training",
      upTo: "Up to"
    },
    game: {
      queue: "Queue",
      completed: "Completed",
      nextUp: "Next Up",
      more: "more",
      pass: "PASS",
      backspace: "Backspace",
      dragMe: "Drag Me"
    },
    report: {
      title: "🚀 Yancy’s Mathetris Report",
      accuracyScore: "Accuracy Score",
      questions: "Questions",
      correct: "Correct",
      totalTime: "Total Time",
      incorrect: "Incorrect",
      footer: "Scroll down to see the worksheet view or click \"Export Image\" to save.",
      backMenu: "Back to Menu",
      exportImg: "Export Image",
      printPdf: "Print PDF",
      name: "Name:",
      date: "Date:",
      time: "Time:",
      sign: "Sign:",
      generatedBy: "Generated by 🚀 Yancy’s Mathetris"
    }
  },
  cn: {
    appTitle: "🚀 Yancy’s Mathetris",
    config: {
      maxNumber: "题目数值范围",
      maxAnswer: "答案最大数值",
      steps: "计算步数",
      position: "填空位置",
      posRight: "右侧 (a + b = ?)",
      posLeft: "左侧 (? + b = c)",
      posMixed: "混合",
      speed: "目标时间 (速度)",
      secPerProb: "秒 / 每题",
      totalQ: "题目数量",
      randomDiff: "难度随机化",
      randomDiffDesc: "混合更简单的题型",
      instantFeedback: "即时反馈",
      instantFeedbackDesc: "答错时立即提示",
      startBtn: "开始训练",
      upTo: "以内"
    },
    game: {
      queue: "待做",
      completed: "已完成",
      nextUp: "下一题",
      more: "更多",
      pass: "跳过",
      backspace: "回退",
      dragMe: "拖动我"
    },
    report: {
      title: "🚀 Yancy’s Mathetris 报告",
      accuracyScore: "正确率",
      questions: "题目总数",
      correct: "答对",
      totalTime: "总用时",
      incorrect: "答错",
      footer: "向下滑动查看作业卷视图，或点击“保存图片”下载。",
      backMenu: "返回菜单",
      exportImg: "保存图片",
      printPdf: "打印 PDF",
      name: "姓名:",
      date: "日期:",
      time: "用时:",
      sign: "签名:",
      generatedBy: "生成于 🚀 Yancy’s Mathetris"
    }
  }
};

export const getT = (lang: Language) => translations[lang];